# Generated by Django 2.0.2 on 2018-02-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='id',
        ),
        migrations.AlterField(
            model_name='commit',
            name='git_hash',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
